### ISSUE TITLE
Fixed lot size

### ISSUE THREAD

**Issue by yairelmaliah** [stfl/backtestd-expert#13]
Adding fixed lot size optimization with no tp or sl , only entry and exit indi

**Comment by stfl** [comment]
This should be fairly straight forward. I don't have the dev environmant on this machine but you can add this by changing the following to MoneyFixedLot. I think that's the name of the class which is part of the standard library provided by MQL5

https://github.com/stfl/backtestd-expert/blob/6f39c4f06ff7364458afc832e964eca9e32dd1d4/Experts/backtestd/backtestd-expert.mq5#L573

make sure you add the #include accordingly on top..

The money object in BacktestExpert is of type Money which is the interface MoneyFixedRisk implements.

https://github.com/stfl/backtestd-expert/blob/6f39c4f06ff7364458afc832e964eca9e32dd1d4/Include/backtestd/Expert/BacktestExpert.mqh#L62

**Comment by stfl** [comment]
Btw. my personal oppinion.. You need to consider that a fixed lot will not give you an accurate result.
